name: platformio ESP8266

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        pip install -U platformio
        platformio update
    - name: Test with pytest
      run: |
        python --version
        platformio lib builtin -h
        platformio run
        cd .pio/build/nodemcuv2
        ls -ltr

